languange: php
php:
 - '7.1.11'
 - hhvm
 - nightly
script:
  - composer install --no-ansi --no-interaction --no-progress --no-scripts --optimize-autoloader
  - composer run test
  - rm -rf vendor
  - composer install --no-ansi --no-dev --no-interaction --no-progress --no-scripts --optimize-autoloader