language: php
php:
- '7.3'
- '7.4'
script:
- if find . -name "*.php" ! -path "./vendor/*" -print0 | xargs -0 -n 1 -P 8 php -l
  | grep -v "No syntax errors detected"; then exit 1; fi
- composer install --no-ansi --no-interaction --no-progress --no-scripts --optimize-autoloader
- composer run test
- composer run lint
- rm -rf vendor
- composer install --no-ansi --no-dev --no-interaction --no-progress --no-scripts
  --optimize-autoloader
before_deploy:
- mkdir dist
- cp LICENSE dist
- cp .htaccess dist
- cp -r logs dist
- cp -r public dist
- cp -r src dist
- cp -r vendor dist
- rm -f dist/logs/app.log
- zip -r planroom-api-${TRAVIS_TAG}.zip dist
deploy:
  provider: releases
   api-key:
    secure: Cj9RGYfSrNA2FLVIwqODRRjjDII+fCiiZO95HzhqEomG5wSnl2KatSAzzJHRZQXftsR/GUbmTP94dY/QzuKY4hrNiur6+W7Tjn3431Rc8XuEyAZeiRM1UCasiZuvYo73GGN3tqJR/bNECXeOKuN86HgRS5gMFuonLq/AcrlsRHw2B3EaRiU9ZUOAlnWKykNTbmrrJcekG7aSEF7YAd+1SMKc7NFHfl4+nlZ4jKmN588qdh8EB1XBKez0rTHeXMmIRsiPLAWGnaBCHgkw6Qh/kQqUljXqJv2w4Q+IIHHBGFiq4AdvT1jUVtXvkXKptQkcH16mzA89xTTDFAPRSBlGd8d82cHRWRPYXUPl3vhZWk1sl+fSmCCK6pK6bvgu0ioi+U0MArj1rff5PJ+krbJ8FNtFPm4245pM+HNYETI06S8P3wJUC9BCV/3gp8sfdIv3kw//89BzOYxjBH9Jb36tmKeOH0tJXv4xC/w5DiJ6YQoCI4Ly8s9v6cMJRVHvtflbESuk/aZRTI0SaAfvsUxV16Agpvm68R/+4n1FMUIxJ0fNSdtOuo2sBS414806wJIHJpESFAxBBhLRMg1skv2DROPf986yn+0CQHFAtFyeyl8hVAtNH/BSVBAhW3v666MVqTNY1GSKX+SYYJYMitKQGTv8zNCwYsSSmB9K07zdqA8=
  file: planroom-api-${TRAVIS_TAG}.zip
  skip_cleanup: true
  on:
    tags: true
    php: '7.4'

